### ISSUE TITLE
Command-line version

### ISSUE THREAD

**Issue by SEAPUNK** [eknkc/amber#32]
I just saw amber, and from the readme, it looks absolutely awesome!

One thing that I wish you'd add is a standalone command line for amber, so you could compile amber files without having to write a script that does that.

**Comment by xyproto** [comment]
Here is one possible workaround:

You can run [Algernon](https://github.com/xyproto/algernon) like this:

`algernon index.amber'

Then download the rendered file with curl:

`curl -o index.html http://localhost:3000/`

**Comment by eknkc** [comment]
Sorry for extremely late answer, there is a cli.

```
go install github.com/eknkc/amber/amberc
```

then use `amberc input.amber`

It's really not sophisticated though.
