### ISSUE TITLE
Inconsistent order of attribute iteration

### ISSUE THREAD

**Issue by zserge** [eknkc/amber#39]
Currently attributes are put into a map in `Compiler.visitTag()` method. Since Go uses randomized order of iteration for maps - this results in different HTML files generated from the same amber file every time you compile them.

This implies that one can't keep compiled HTMLs under version control because amber compilation is not reproducible. Also, one can't test amber templates because the HTML output is always random, so you can't compare it to a certain expected value.

A possible fix would be to keep attributes in a slice and use a special node pointer for the special `class` attribute.

P.S. On a side note, is this project still alive? Most open issues are half a year old.. Amber seems to be the only sane lightweight HTML markup compiler for Go, it would be a big loss if it's not under development anymore.

**Comment by zserge** [comment]
I've made a quick pull request to fix this issue: https://github.com/eknkc/amber/pull/40

**Comment by eknkc** [comment]
Oh hey!

I just made them sorted in lexical order before seeing your PR. I guess your solution makes more sense that it reflects the amber input to html output. Should we revert this and go with yours?

I've been using Amber in prod but on low key stuff to be honest. Never had a chance to work on the internals or extend the capabilities, just bugfixes and basic maintenance. Planning to overhaul the parser and emitter on a v2 branch though.

**Comment by zserge** [comment]
Glad to hear the project is still alive, and thanks for the prompt response!

I'm now writing a simple static blog generator, which uses Amber internally, and my tests were failing because of inconsistent attributes. So for my use case it doesn't matter if the keys are sorted or not, as long as the order is the same every time I run the tests.

I think you approach is more readable - first build a map, then define the order of keys, then iterate in this order. Mine saves you from another loop, but I don't think it's critical, since the number of keys is normally small. So I think you may close my PR and leave your solution as it is now.
