### ISSUE TITLE
Input close tag

### ISSUE THREAD

**Issue by susilolab** [eknkc/amber#44]
I have asked in the golang g+ forum about this issue, i can't generate output like this using amber:
&lt;input type="text" name="email" size="30" /&gt;

they are always give result like this
&lt;input type="text" name="email" size="30"&gt;&lt;/input&gt;
so what i want is just that simple. my question: is it by design or not yet implemented?
thanks

**Comment by eknkc** [comment]
Self closing tags are pre defined here:

https://github.com/eknkc/amber/blob/master/parser/nodes.go

I think I got the list from Jade and I'm not sure why input is not there. I don't think there is a case where input should not be self closing.

Gonna check the spec and have it self closing if it's safe.

**Comment by susilolab** [comment]
ok, thanks

**Comment by eknkc** [comment]
I can't seem to reproduce this, see: https://github.com/eknkc/amber/blob/master/samples/input.html

Can you provide a test case?

**Comment by susilolab** [comment]
I'm sorry, this is my fault the problem disappeared after I updated package.
