### ISSUE TITLE
Attributes do not accept variables

### ISSUE THREAD

**Issue by nii236** [eknkc/amber#48]
```
!!!5
html
    import ./partials/header.amber
    body.ma0.min-vh-100
        p #{Site.BaseURL}
        div.min-vh-100.cover[style="background-image:url(#{Site.BaseURL}/img/flower.jpg); background-position: center;"]
```

From the above, 

```
p #{Site.BaseURL}
```

Results in `http://localhost:1313/stephandjohn/`

But 

```
div.min-vh-100.cover[style="background-image:url(#{Site.BaseURL}/img/flower.jpg); background-position: center;"]
```

Results in `(#{Site.BaseURL}/img/flower.jpg)` instead of `(http://localhost:1313/stephandjohn//img/flower.jpg)`.

I am using [Hugo](gohugo.io) by the way, I'm not sure if this matters.

**Comment by fanmanpro** [comment]
~~@nii236 Found a solution to this in the meantime by any chance?~~

Nevermind, found that using [Expressions](https://github.com/eknkc/amber#expressions) solves my issue
