### ISSUE TITLE
Cannot import templates in nested directory, is it supported?

### ISSUE THREAD

**Issue by anirudh-chhangani** [eknkc/amber#49]
+templates
 +components
 --test.amber
 -main.amber
```
test.amber
div#somid hello

main.amber
....
body 
     import test.amber
```

does not work.

How would you import templates from a directory?

**Comment by eknkc** [comment]
`import components/test.amber` should work.

**Comment by anirudh-chhangani** [comment]
ahh yeah, thanks a lot, it works 👍
